version: '3'

services:
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./laravel:/var/www:z
      - ./default.conf:/etc/nginx/conf.d/default.conf:z
    ports:
      - "80:80"
    tty:  true
    restart: unless-stopped
    container_name: nginx1.23
    depends_on:
      - php74

  php74:
    build:
      context: .
      dockerfile: Dockerfile
    tty:  true
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - ./laravel:/var/www:z
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf:z
    container_name: php74
